### PR TITLE
Release 1.0 RC1

### PR DESCRIPTION
**Pull request by jnicklas**
This releases an RC candidate for interactors core and html, also releasing version 5.0.rc1 for material UI interactors

### CODE REVIEW

**Review by cowboyd — APPROVED** [review]
ZOMG INTERACTORS IS HERE 🥳 🥳🥳

**Comment by wKich** [comment]
@cowboyd Looks like we released the wrong version of material-ui interactors :( I thought we wanted to use 4.x version to support material-ui components from 4.x branch and up major version when we are ready to ship them for material-ui 5.x version

**Comment by cowboyd** [comment]
You are correct. Well we can still release 4.0, just means we'll have a bogus 5.0.0-rc1.0 hanging around when we get to 5.0

**Comment by wKich** [comment]
Yeah, that's right.

**Pull request merged**
