### PR TITLE
Add dropdown for `html` & `mui` API links

### PR DESCRIPTION
**Pull request by minkimcello**
## Motivation

There's no way for users to find the deployed API sites for `@interactors/html` and `@interactors/material-ui` from the interactors website.

## Approach

- Renamed `Docs` to `Guides` (this is also how it's labelled on our effection site)
- These components are nested on top of each other so I had no choice but to swizzle `navbaritem` in order to add our own styles
- Had to bump docusaurus from `beta.3` to `beta.4` because despite their `.3` docs, the navbar dropdown wasn't actually implemented until `.4`

### Old
www.frontside.com/interactors
Screen Shot 2021-11-16 at 12 07 27 PM

### New
https://deploy-preview-134--interactors.netlify.app/interactors/
Screen Shot 2021-11-16 at 12 07 45 PM

### CODE REVIEW

**Comment by jnicklas** [comment]
I'm assuming that all of the code added is copied in from docusaurus, but is there any way we can do this without copying in so much? It'll be hard to tell where we actually modified something. In that case, I think I'd prefer an intermediate page.

**Comment by minkimcello** [comment]
@jnicklas Yeah it's an all-or-nothing situation when we swizzle a component. If we're going to create an intermediate page, I think Jorge will need to get involved otherwise it'll end up being an empty page with two URLs if I do it.

But I think it makes more sense to combine the two api docs into one. Unless there was prior conversation about it, I'm assuming the reason why `@interactors/html` and `@interactors/material-ui` each have their own typedoc sites was out of convenience? @wKich could you chime in?

So instead of:
```
interactors-site
  api-page-or-dropdown
    link-to-html-api-site
      @html
    link-to-mui-api-site
      @mui
```

Shouldn't it be:
```
interactors-site
  api-link
    interactors-api-site
      @html
      @mui
```

**Comment by minkimcello** [comment]
It might be best to keep it separate for now. I tried to put them together but one downside I found was that it doesn't display individual package versions for monorepos.

**Comment by minkimcello** [comment]
@jorgelainfiesta Thoughts? Swizzle navbaritem or create a separate page for the api doc links?

**Review by jnicklas — APPROVED** [review]

**Pull request merged**
